project_id = "txsbiergktqyhfyxoqwg"

[functions.get-razorpay-key]
verify_jwt = false

[functions.create-demo-users]
verify_jwt = false

[functions.reset-demo-password]
verify_jwt = false

[functions.daily-ingredient-push]
verify_jwt = false

[functions.attendance-auto-closure]
verify_jwt = false
